import { HabitTemplate } from '../entities/habit-template.entity';
import { HabitFrequency } from '../entities/habit.entity';

export const defaultHabitTemplates: Partial<HabitTemplate>[] = [
  {
    name: 'Morning Exercise',
    description: '30 minutes of cardio or strength training',
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    color: '#FF6B6B',
    icon: '🏃',
    category: 'Fitness',
    goals: ['fitness', 'health', 'weight-loss'],
    isDefault: true,
  },
  {
    name: 'Drink 8 Glasses of Water',
    description: 'Stay hydrated throughout the day',
    frequency: HabitFrequency.DAILY,
    targetCount: 8,
    color: '#4ECDC4',
    icon: '💧',
    category: 'Health',
    goals: ['health', 'wellness'],
    isDefault: true,
  },
  {
    name: 'Read for 30 Minutes',
    description: 'Read books, articles, or educational content',
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    color: '#95E1D3',
    icon: '📚',
    category: 'Learning',
    goals: ['learning', 'personal-growth', 'education'],
    isDefault: true,
  },
  {
    name: 'Meditate',
    description: '10-15 minutes of mindfulness or meditation',
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    color: '#A8E6CF',
    icon: '🧘',
    category: 'Mental Health',
    goals: ['mental-health', 'wellness', 'stress-reduction'],
    isDefault: true,
  },
  {
    name: 'Healthy Meal Prep',
    description: 'Prepare nutritious meals',
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    color: '#FFE66D',
    icon: '🥗',
    category: 'Nutrition',
    goals: ['health', 'nutrition', 'weight-loss'],
    isDefault: true,
  },
  {
    name: 'Practice Gratitude',
    description: 'Write down 3 things you are grateful for',
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    color: '#FF9A8B',
    icon: '🙏',
    category: 'Mental Health',
    goals: ['mental-health', 'personal-growth', 'happiness'],
    isDefault: true,
  },
  {
    name: 'Learn a New Skill',
    description: 'Spend time learning something new',
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    color: '#B4A7D6',
    icon: '🎓',
    category: 'Learning',
    goals: ['learning', 'personal-growth', 'career'],
    isDefault: true,
  },
  {
    name: 'Sleep 8 Hours',
    description: 'Get adequate rest for recovery',
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    color: '#6C5CE7',
    icon: '😴',
    category: 'Health',
    goals: ['health', 'wellness', 'recovery'],
    isDefault: true,
  },
  {
    name: 'Take Vitamins',
    description: 'Daily vitamin and supplement routine',
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    color: '#FDA7DF',
    icon: '💊',
    category: 'Health',
    goals: ['health', 'wellness'],
    isDefault: true,
  },
  {
    name: 'Connect with Family',
    description: 'Call or message family members',
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    color: '#F8B500',
    icon: '👨‍👩‍👧‍👦',
    category: 'Relationships',
    goals: ['relationships', 'family', 'social'],
    isDefault: true,
  },
  {
    name: 'Stretch or Yoga',
    description: '15 minutes of stretching or yoga',
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    color: '#74B9FF',
    icon: '🤸',
    category: 'Fitness',
    goals: ['fitness', 'flexibility', 'wellness'],
    isDefault: true,
  },
  {
    name: 'Limit Screen Time',
    description: 'Reduce phone and computer usage',
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    color: '#A29BFE',
    icon: '📵',
    category: 'Digital Wellness',
    goals: ['mental-health', 'productivity', 'wellness'],
    isDefault: true,
  },
  {
    name: 'Journal',
    description: 'Write in your daily journal',
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    color: '#DFE6E9',
    icon: '📝',
    category: 'Personal Growth',
    goals: ['personal-growth', 'mental-health', 'self-reflection'],
    isDefault: true,
  },
  {
    name: 'Clean and Organize',
    description: 'Tidy up living or work space',
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    color: '#00B894',
    icon: '🧹',
    category: 'Lifestyle',
    goals: ['organization', 'productivity', 'wellness'],
    isDefault: true,
  },
  {
    name: 'Practice Instrument',
    description: 'Practice your musical instrument',
    frequency: HabitFrequency.DAILY,
    targetCount: 1,
    color: '#FDCB6E',
    icon: '🎸',
    category: 'Hobbies',
    goals: ['hobbies', 'creativity', 'learning'],
    isDefault: true,
  },
];
